version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  ssacp:
    build: ./ssacp
    container_name: ssacp  
    volumes:
      - ./ssacp:/app      
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - PYTHONUNBUFFERED=1 
      - MONGO_URL=mongodb://root:example@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&authSource=admin

  carro1:
    build: ./carro
    environment:
      - CAR_ID=1
    depends_on:
      - mqtt_broker
  
  carro2:
    build: ./carro
    environment:
      - CAR_ID=2
    depends_on:
      - mqtt_broker

  isccp1:
    build: ./isccp
    environment:
      - NAME=ISCCP1
    depends_on:
      - mqtt_broker

  isccp2:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker

  mongo1:
    build: ./mongo           
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./mongo1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo2:
    build: ./mongo           
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./mongo2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo3:
    build: ./mongo          
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./mongo3:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ssvcp:
    build: ./ssvcp
    ports:
      - "8000:8000"  # A porta externa para vocÃª acessar
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - MONGO_URL=mongodb://root:example@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&authSource=admin