version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  ssacp:
    build: ./ssacp
    container_name: ssacp  
    volumes:
      - ./ssacp:/app      
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - PYTHONUNBUFFERED=1 
      - MONGO_URL=mongodb://root:example@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&authSource=admin

# Carros

  carro1:
    build: ./carro
    container_name: carro1
    restart: always
    environment:
      - CAR_ID=1
    depends_on:
      - mqtt_broker

  carro2:
    build: ./carro
    container_name: carro2
    restart: always
    environment:
      - CAR_ID=2
    depends_on:
      - mqtt_broker

  carro3:
    build: ./carro
    container_name: carro3
    restart: always
    environment:
      - CAR_ID=3
    depends_on:
      - mqtt_broker

  carro4:
    build: ./carro
    container_name: carro4
    restart: always
    environment:
      - CAR_ID=4
    depends_on:
      - mqtt_broker

  carro5:
    build: ./carro
    container_name: carro5
    restart: always
    environment:
      - CAR_ID=5
    depends_on:
      - mqtt_broker

  carro6:
    build: ./carro
    container_name: carro6
    restart: always
    environment:
      - CAR_ID=6
    depends_on:
      - mqtt_broker

  carro7:
    build: ./carro
    container_name: carro7
    restart: always
    environment:
      - CAR_ID=7
    depends_on:
      - mqtt_broker

  carro8:
    build: ./carro
    container_name: carro8
    restart: always
    environment:
      - CAR_ID=8
    depends_on:
      - mqtt_broker

  carro9:
    build: ./carro
    container_name: carro9
    restart: always
    environment:
      - CAR_ID=9
    depends_on:
      - mqtt_broker

  carro10:
    build: ./carro
    container_name: carro10
    restart: always
    environment:
      - CAR_ID=10
    depends_on:
      - mqtt_broker

  carro11:
    build: ./carro
    container_name: carro11
    restart: always
    environment:
      - CAR_ID=11
    depends_on:
      - mqtt_broker

  carro12:
    build: ./carro
    container_name: carro12
    restart: always
    environment:
      - CAR_ID=12
    depends_on:
      - mqtt_broker

  carro13:
    build: ./carro
    container_name: carro13
    restart: always
    environment:
      - CAR_ID=13
    depends_on:
      - mqtt_broker

  carro14:
    build: ./carro
    container_name: carro14
    restart: always
    environment:
      - CAR_ID=14
    depends_on:
      - mqtt_broker

  carro15:
    build: ./carro
    container_name: carro15
    restart: always
    environment:
      - CAR_ID=15
    depends_on:
      - mqtt_broker

  carro16:
    build: ./carro
    container_name: carro16
    restart: always
    environment:
      - CAR_ID=16
    depends_on:
      - mqtt_broker

  carro17:
    build: ./carro
    container_name: carro17
    restart: always
    environment:
      - CAR_ID=17
    depends_on:
      - mqtt_broker

  carro18:
    build: ./carro
    container_name: carro18
    restart: always
    environment:
      - CAR_ID=18
    depends_on:
      - mqtt_broker

  carro19:
    build: ./carro
    container_name: carro19
    restart: always
    environment:
      - CAR_ID=19
    depends_on:
      - mqtt_broker

  carro20:
    build: ./carro
    container_name: carro20
    restart: always
    environment:
      - CAR_ID=20
    depends_on:
      - mqtt_broker

  carro21:
    build: ./carro
    container_name: carro21
    restart: always
    environment:
      - CAR_ID=21
    depends_on:
      - mqtt_broker

  carro22:
    build: ./carro
    container_name: carro22
    restart: always
    environment:
      - CAR_ID=22
    depends_on:
      - mqtt_broker

  carro23:
    build: ./carro
    container_name: carro23
    restart: always
    environment:
      - CAR_ID=23
    depends_on:
      - mqtt_broker

  carro24:
    build: ./carro
    container_name: carro24
    restart: always
    environment:
      - CAR_ID=24
    depends_on:
      - mqtt_broker

# Torres (ISSCP)

  isccp1:
    build: ./isccp
    environment:
      - NAME=ISCCP1
    depends_on:
      - mqtt_broker
  isccp2:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp3:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp4:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp5:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp6:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp7:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp8:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp9:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp10:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp11:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp12:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp13:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp14:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker
  isccp15:
    build: ./isccp
    environment:
      - NAME=ISCCP2
    depends_on:
      - mqtt_broker


  mongo1:
    build: ./mongo           
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./mongo1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo2:
    build: ./mongo           
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./mongo2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo3:
    build: ./mongo          
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./mongo3:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ssvcp:
    build: ./ssvcp
    ports:
      - "8000:8000"  # Porta de acesso
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - MONGO_URL=mongodb://root:example@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0&authSource=admin
    restart: on-failure

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: "no"
    command: >
      bash -c "
      echo 'Aguardando os servidores Mongo subirem...' &&
      sleep 10 &&
      mongosh --host mongo1:27017 -u root -p example --authenticationDatabase admin --eval '
        try {
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo1:27017\" },
              { _id: 1, host: \"mongo2:27017\" },
              { _id: 2, host: \"mongo3:27017\" }
            ]
          });
          print(\"Replica Set INICIADO com sucesso!\");
        } catch (e) {
          if (e.codeName === \"AlreadyInitialized\") {
            print(\"Replica Set JA EXISTE. Nenhuma acao necessaria.\");
          } else {
            print(\"Erro ao iniciar: \" + e);
          }
        }
      '
      "